
            #  QUESTION
                 
                 # WE ARE GoING   TO  WRITE  A PROGRAM  THAT GENERATES A RANDOM  NUMBER 
                 # AND ASKS THE USER  TO GUESS IT.
        
       # IF THE PLAYER'S GUESS  IS HIGHER THAN ACTUAL NUMBER , THE PROGRAM DISTPLAYS "LOWER  NUMBER PLEASE."
  
       # SIMILARLY IF THE USER'S  GUESS  IS TOO LOW , THE PROGRAM PRINTS "HIGHER NUMBER PLEASE."

       # WHEN THE USER GUESS'S THE WRITE NUMBER, THE PROGRAM DISPLAYS THE NUMBER OF GUESSES THE PLAYER 
     
       # USED TO ARRIVE AT THE NUMBER.

     # HINT : USE THE RANDOM MODULE   
     